#!/usr/bin/env python3 

import subprocess 
from subprocess import PIPE, CalledProcessError

def getcfgvol():
    global cfgVol
    spout = subprocess.run(['awsstat'], stdout=subprocess.PIPE)
    for line in spout.stdout.splitlines():
        if (b"CFG1" in line):
            cfgVol = line.split()[5].decode()

def getnetv_globals():
    try:
        subprocess.run(["pdsUtil", cfgVol, "NETVIEW.CNM01.CNMCLST/GLBCNM01", "--extract"],stdout=PIPE,check=True)
    except subprocess.CalledProcessError as err:
        print(err)
        print("Unable to obtain Netview Globals configuration file, not able to continue")
        print("Verify you are currently in the directory where the zPDT volumes reside. (eg. /home/ibmsys1/zdt/volumes/")
        sys.exit()

getcfgvol()
getnetv_globals()

tasklist = []
tasklist.append([])
tasklist[0].append('MVS')
tcnt = 0
tlist = open('GLBCNM01.txt', "r")
for line in tlist:
    if "TASK.X ' = " in line:
        taskname = (line.split()[4].strip('\"\''))
        if taskname != 'MVS':
            tasklist.append([])
            tcnt+=1
            tasklist[tcnt].append(taskname)
    if "PARN.X ' = " in line and taskname != 'MVS':
        parent = line.split()[4].strip('\"\'').replace(',', ' ')
        for words in parent.split():
            tasklist[tcnt].append(words)
tlist.close()
for words in tasklist:
    print(words)
